version: '3'
services:
    mosquitto:
        build: .
        restart: always
        volumes:
            - "/etc/localtime:/etc/localtime:ro"
            - "/etc/timezone:/etc/timezone:ro"
            - "/opt/container/mosquitto/config:/opt/mosquitto/config"
            - "/opt/container/mosquitto/data:/opt/mosquitto/data"
            - "/opt/container/mosquitto/log:/opt/mosquitto/log"
        ports:
            - "1883:1883"
            - "9001:9001"
        tty: true
        environment:
            USER_ID: "1001"
            GROUP_ID: "1001"
